### ISSUE TITLE
Case sensitivity of monger group statistics and search

### ISSUE THREAD

**Issue by racke** [interchange/Perl-Dancer-Conference#103]
If an user enters hannover.pm instead of Hannover.pm, we end up with two entries in the statistics and also the search would find only one of them.

ACT has a similar problem (from IRC yesterday):

http://act.yapc.eu/ye2016/stats shows London.pm with 20, but
http://act.yapc.eu/ye2016/search?pm_group=London.pm only shows 19
http://act.yapc.eu/ye2016/search?pm_group=london.pm

Regards
               Racke

**Comment by SysPete** [comment]
Fixed via 3e11477a7881e7757749832dcf466eb3756c56e2.
