### ISSUE TITLE
News

### ISSUE THREAD

**Issue by racke** [interchange/Perl-Dancer-Conference#15]
Add news section, based on Message class.

**Comment by racke** [comment]
News can be added now, another nice thing would be to have an uri for the news item. :-)

**Comment by SysPete** [comment]
Added along with routes and view updates.

**Comment by racke** [comment]
Excellent :+1:, thanks a lot! Just needs a few more adjustments so it really shines :-). For example, paragraphs are lost when you edit an existing item.

**Comment by racke** [comment]
Other things I can think of is showing only part of the news on the front page (if it is long text) and maybe an extra column in messages for a short summary of the whole message (Interchange6::Schema addition).

What do you think?

**Comment by SysPete** [comment]
I think for homepage we should perhaps only show last 2 news items along with a link to /news to access all news.

I've created a new ic6s ticket for summary/teaser.

**Comment by racke** [comment]
On 07/28/2015 12:30 PM, Peter Mottram wrote:
> I think for homepage we should perhaps only show last 2 news items along with a link to /news to access all news.
> 
> I've created a new ic6s ticket for summary/teaser.
> 

Yes, I agree.

Regards
	Racke

**Comment by SysPete** [comment]
closed by f3fe1ce151cbf5834d6e9673995c62784ed263ff
