### ISSUE TITLE
Conference Ticket Class

### ISSUE THREAD

**Issue by racke** [interchange/Perl-Dancer-Conference#20]
I'm going to add a table to link conferences with tickets (products) in order to determine whether an user bought a ticket for the conference.

**Comment by SysPete** [comment]
How about adding a column to ConferenceAttendee?

**Comment by racke** [comment]
We still need to know which product / ticket is related to a conference - we also might sell other merchandise.
It would be also useful to "tag" product as ticket.

**Comment by racke** [comment]
Ticket class added.
