### ISSUE TITLE
home :: speakers container explodes in mobile.

### ISSUE THREAD

**Issue by sbatschelet** [interchange/Perl-Dancer-Conference#25]
this is probably due to varied heights perhaps we could deply something like this.  I used this in Angler with some success.

https://github.com/PaulSpr/jQuery-Equal-Height-Columns

* this obviously also occurs in the speaker page.

**Comment by racke** [comment]
Screen size / device / screen shot?

**Comment by sbatschelet** [comment]
more details soon iphone 5
