### ISSUE TITLE
/profile nav improvements for multiple orders.

### ISSUE THREAD

**Issue by hexfusion** [interchange/Perl-Dancer-Conference#32]
/profile nav menu 'View your conference ticket' should read 'View your conference tickets' and link to  profile/order if $orders are greater then 1. Currently we only show ->first.

**Comment by SysPete** [comment]
There is already a basic /profile/orders route implemented that we could use instead. @racke?

**Comment by sbatschelet** [comment]
@SysPete yes that is what I meant link to 'profile/orders' if $order->count  > 1.  Or yes we could eliminate the option and always use this route regardless. b786485 supports both options.
