### ISSUE TITLE
Event Admin

### ISSUE THREAD

**Issue by racke** [interchange/Perl-Dancer-Conference#42]
We also need a way to get events into the schedule, e.g. "Lunch break", "Lightning talks", "Social event", etc.

**Comment by SysPete** [comment]
Event class added. Still need to hook this into schedule display.

**Comment by SysPete** [comment]
Added but no admin yet so changing issue title to 'Event Admin' since that is the last remaining piece

**Comment by SysPete** [comment]
Event admin complete.
