### ISSUE TITLE
Add scheduled fields to talk

### ISSUE THREAD

**Issue by racke** [interchange/Perl-Dancer-Conference#43]
Boolean value, default FALSE. This would allow admins to prepare the schedule on their own time without being visible to the world (and the attendee itself).

**Comment by SysPete** [comment]
Perhaps we should add this flag to Conference class so it is a simple global for the conference? Perhaps call it 'display_schedule' or something?

**Comment by racke** [comment]
Global flag doesn't cover all use cases. For example we might display training courses on schedule before presentations.

**Comment by SysPete** [comment]
Done. Also added to Event.
