### ISSUE TITLE
talk workflow

### ISSUE THREAD

**Issue by hexfusion** [interchange/Perl-Dancer-Conference#50]
proposed workflow
- from admin on post accepted changed to true
- email dispatched to user with confirmation email
- user clicks link updating confirmed to true
- talk displayed

currently we show talk if accepted is true and confirmed is false.

**Comment by racke** [comment]
Currently we show talk if accepted is true and confirmed is true. Sorry for the confusion.

**Comment by SysPete** [comment]
@racke you're behinf the code here. ;-)  Talks are shown to non-admin users if accepted is true. Confirmed is ignored atm and this matches behaviour I've seen in Act.

**Comment by racke** [comment]
Aha :-/

**Comment by sbatschelet** [comment]
act functionality will remain email will be sent on post.
