### ISSUE TITLE
centralizing data validation/validator methods

### ISSUE THREAD

**Issue by sbatschelet** [interchange/Perl-Dancer-Conference#52]
We have some crossover with Admin and User in regards to validation requirements.  example Talks https://github.com/interchange/Perl-Dancer-Conference/blob/master/lib/PerlDance/Routes/Profile.pm#L857 this method would be useful in Admin as well.  Validation of other data is on the TODO so I would find this useful.

I propose PerlDance::Validate

**Comment by racke** [comment]
It makes sense to share code. It would be also good to write tests for the validation code.

**Comment by SysPete** [comment]
Closed now all validation is handled by Dancer::Plugin::DataTransposeValidator. Last commit in series was ca837b6064e59a0ee6b96e70709deceabfa52dfc
