### ISSUE TITLE
sponsor package proposal

### ISSUE THREAD

**Issue by sbatschelet** [interchange/Perl-Dancer-Conference#56]
Hard to excite sponsors without packages.  Here is a start based on last year. please comment.

* Bronze Level Sponsor: Web logo with link on event homepage and other web based marketing and email blasts. - 200.00
* Silver Level Sponsor: Bronze level sponsorship and company banner in conference room. - 350.00
* Platinum Sponsor: Gold level sponsorship and company logo predominantly placed on event t-shirt. - 950.00
* Diamond Sponsor: Platinum level sponsorship, and event sponsor including 1 training pass. - 3500.00

**Comment by racke** [comment]
Notes:
   
* We can't promise videos.
* Diamond sponsor = social event sponsor, don't think we need to promise 4 passes.

**Comment by racke** [comment]
One pass would be enough, training is really limited.

**Comment by sbatschelet** [comment]
@yure @SysPete  any additional input?

**Comment by SysPete** [comment]
As @racke says we cannot promise videos so Gold is gone. Nothing else to add atm.

**Comment by racke** [comment]
Sponsoring page updated.
