### ISSUE TITLE
list of potential sponsors

### ISSUE THREAD

**Issue by sbatschelet** [interchange/Perl-Dancer-Conference#57]
added to finance spreadsheet

**Comment by sbatschelet** [comment]
maybe easier to have a spreadsheet hosted by the spawn of satan :smiling_imp: Ghoulgle

**Comment by racke** [comment]
It should be in a private place only accessible for organizators.

**Comment by sbatschelet** [comment]
@racke can we add spreadsheet for these matters like we do with finance?

**Comment by racke** [comment]
I guess we can also add that to finance spreadsheet. What do you think, @SysPete

**Comment by sbatschelet** [comment]
can I be updated with link to new spreadsheet please

**Comment by sbatschelet** [comment]
I have added 30 potential sponsors please look at the list and add any notes or contacts you may have to assist in sales efforts.

**Comment by racke** [comment]
Not relevant any more.
