### ISSUE TITLE
layout with sidebar

### ISSUE THREAD

**Issue by sbatschelet** [interchange/Perl-Dancer-Conference#59]
To give an area for sponsors I have added a sidebar to the layout.  Although first talking with SysPete we thought about 10 - 2.  It seems 9 - 3 gives a little better look.  Also to do this we needed to remove use of the container class where they now become nested.

I made a few other proposed changes to the index view including removing the jumbotron class and replacing it with a simple well.  I also think we could consider putting the news on the sidebar.  Look it over and see what you think.

the branch is people/hexfusion/new-template

**Comment by sbatschelet** [comment]
This explains why nested containers are wrong.  So in the original design we didn't have nested containers but because the content and sidebar are wrapped in a container it causes the problem with content.  I believe the remedy would be to replace container with row in content views.

http://www.helloerik.com/the-subtle-magic-behind-why-the-bootstrap-3-grid-works

**Comment by SysPete** [comment]
closed by 5ad0cfcbadca002fa8014f9f20c245316104bfbf
