### ISSUE TITLE
wiki users links

### ISSUE THREAD

**Issue by melmothx** [interchange/Perl-Dancer-Conference#64]
[user:XYZ] is case sensitive, unclear if this is fine or not.

Also I couldn't find a clear way to set or see which my own username is (I think none).

**Comment by racke** [comment]
You can use either nickname or username (email). Also we should prevent submitting bogus usernames.

**Comment by SysPete** [comment]
So we should accept all of the following:
[me], [user:nickname], [user:username]
where [me] is converted to [user:username] and then display like:
[Peter Mottram (SysPete)](https://www.perl.dance/users/5-Peter-Mottram)
Sound reasonable?

**Comment by racke** [comment]
:+1:
