### ISSUE TITLE
Add SPF record for perl.dance

### ISSUE THREAD

**Issue by SysPete** [interchange/Perl-Dancer-Conference#7]
improve spam scoring

**Comment by racke** [comment]
Good idea, please add the string to put into the DNS :-).

**Comment by SysPete** [comment]
bind record which allows perl.dance mail to be sent from perl.dance A
record and MX (mail.linuxia.de) with anything else rejected:

perl.dance.  IN TXT "v=spf1 mx a -all"

**Comment by racke** [comment]
Moved MX and added SPF.

**Comment by SysPete** [comment]
perl.dance descriptive text "v=spf1 a ip4:217.70.176.0/20 ip6:2001:4b98:c::/48 ptr ?all"
